# Generated by Django 3.2.6 on 2022-09-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='uls1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='uls2',
            field=models.TextField(null=True),
        ),
    ]
