# Generated by Django 3.2.6 on 2022-09-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220921_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='uls1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='uls2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.IntegerField(default=1),
        ),
    ]
